const filtersDB = {
  programmingLanguages: [
    { id: 1, name: "C" },
    { id: 2, name: "C++" },
    { id: 3, name: "C#" },
    { id: 4, name: "Go" },
    { id: 5, name: "Java" },
    { id: 6, name: "JavaScript" },
    { id: 7, name: "Kotlin" },
    { id: 8, name: "R" },
    { id: 9, name: "Objective-C" },
    { id: 10, name: "PHP" },
    { id: 11, name: "Postscript" },
    { id: 12, name: "Python" },
    { id: 13, name: "React" },
    { id: 14, name: "Ruby" },
    { id: 15, name: "Rust" },
    { id: 16, name: "Scala" },
    { id: 17, name: "Scheme" },
    { id: 18, name: "SQL" },
    { id: 19, name: "Swift" },
    { id: 20, name: "TypeScript" },
    { id: 21, name: "Visual Basic. NET" },
    { id: 22, name: "Elixir" },
    { id: 23, name: "Erlang" },
  ],
  level: [
    { id: 1, name: "Junior" },
    { id: 2, name: "Trainee" },
    { id: 3, name: "Mid" },
    { id: 4, name: "Senior" },
    { id: 5, name: "Expert" },
  ],
  workday: [
    { id: 1, name: "Full Time" },
    { id: 2, name: "Part Time" },
    { id: 3, name: "Indeterminate" },
    { id: 4, name: "Freelance" },
    { id: 5, name: "Internship trainee" },
    { id: 6, name: "Temporal" },
  ],
  companyTypes: [
    { id: 1, name: "Startup" },
    { id: 2, name: "Pyme" },
    { id: 3, name: "Multinacional" },
    { id: 4, name: "Medium" },
  ],
};

export default filtersDB;
