/* id, company, name, programming_Languages, description, salary, start, end  */
import { wix, GoogleBlack, meta, windows } from "../public/assets/page";

const jobsTemplate = [
  {
    id: 1,
    company: "Google",
    logo_Company: GoogleBlack,
    name_Vacancy: "Frontend Developer",
    seniority: "Junior", //reemplazar por programming_Level
    programming_Languages: ["React", "Redux", "CSS", "HTML"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus adipisci placeat ipsam ratione maiores veritatis earum eos corporis omnis. Expedita odit ut ipsum accusantium est cupiditate iste praesentium et cumNemo maxime facere expedita aliquam, atque quam laudantium id laboriosam non, a",
    salary: 50000,
    years_of_experience: "2 years",
    workday: "Full_time",
    start: "2023-05-20",
    end: "2024-01-31",
  },
  {
    id: 2,
    company: "Wix",
    logo_Company: wix,
    name_Vacancy: "Backend Developer",
    seniority: "Trainee",
    programming_Languages: ["Node, Express, MongoDB"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl aliquet nunc, vitae al",
    salary: 50000,
    years_of_experience: "2 years",
    workday: "Full_time",
    start: "2023-01-01",
    end: "2024-01-31",
  },
  {
    id: 3,
    company: "Meta",
    logo_Company: meta,
    name_Vacancy: "Data Scientist",
    seniority: "Senior",
    programming_Languages: ["Python, Pandas, Numpy, Matplotlib"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl aliquet nunc, vitae al",
    salary: 50000,
    years_of_experience: "2 years",
    workday: "Full_time",
    start: "2022-01-01",
    end: "2024-01-31",
  },
  {
    id: 4,
    company: "Windows",
    logo_Company: windows,
    name_Vacancy: "Fullstack Developer",
    seniority: "Senior",
    programming_Languages: ["React, Redux, CSS, HTML, Node, Express, MongoDB"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl aliquet nunc, vitae al",
    salary: 50000,
    years_of_experience: "2 years",
    workday: "Full_time",
    start: "2022-01-01",
    end: "2024-01-31",
  },
  {
    id: 5,
    company: "Google",
    logo_Company: GoogleBlack,
    name_Vacancy: "Frontend Developer",
    seniority: "Junior",
    programming_Languages: ["React, Redux, CSS, HTML"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl aliquet nunc, vitae al",
    salary: 50000,
    years_of_experience: "2 years",
    workday: "Full_time",
    start: "2023-05-20",
    end: "2024-01-31",
  },
  {
    id: 6,
    company: "Wix",
    logo_Company: wix,
    name_Vacancy: "Backend Developer",
    seniority: "Trainee",
    programming_Languages: ["Node, Express, MongoDB"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl aliquet nunc, vitae al",
    salary: 50000,
    years_of_experience: "2 years",
    workday: "Full_time",
    start: "2023-01-01",
    end: "2024-01-31",
  },
  {
    id: 7,
    company: "Meta",
    logo_Company: meta,
    name_Vacancy: "Data Scientist",
    seniority: "Senior",
    programming_Languages: ["Python, Pandas, Numpy, Matplotlib"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl aliquet nunc, vitae al",
    salary: 50000,
    years_of_experience: "2 years",
    workday: "Full_time",
    start: "2022-01-01",
    end: "2024-01-31",
  },
  {
    id: 8,
    company: "Windows",
    logo_Company: windows,
    name_Vacancy: "Fullstack Developer",
    seniority: "Senior",
    programming_Languages: ["React, Redux, CSS, HTML, Node, Express, MongoDB"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl aliquet nunc, vitae al",
    salary: 50000,
    years_of_experience: "2 years",
    workday: "Full_time",
    start: "2022-01-01",
    end: "2024-01-31",
  },
];

// id, name, secondname, lastname, secondlastname, birth, age, working, cv, email, password, enfoque1, enfoque2, aboutme, titulos, seniority, logo_Company
const usersTemplate = [
  {
    id: 1,
    name: "Juan",
    lastName: "Perez",
    birthdate: "1990-01-01",
    age: 31,
    working: false,
    country: "Chile",
    email: "iairkap@gmail.com",
    degree: "Software Engineer",
    specialization: "Fullstack Developer",
    languages: ["spanish native", "english advanced"],
    programming_Languages: ["Javascript", "Python", "C++"],
    aboutme:
      "me llamo Juan Perez, estudie en la Universidad de Chile, Ingenieria Civil en Computacion, me especializo en el desarrollo de aplicaciones web, me gusta el trabajo en equipo y soy muy responsable",
    programming_level: "Junior",
    CV: false,
    softskills: ["Communication", "Teamwork", "Leadership"],
    profile_picture:
      "https://images.unsplash.com/photo-1463453091185-61582044d556?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    id: 2,
    name: "Maria",
    lastName: "Rodriguez",
    birthdate: "1995-04-20",
    age: 28,
    working: true,
    country: "Argentina",
    email: "maria.rodriguez@gmail.com",
    degree: "computer science",
    specialization: "Frontend Developer",
    languages: ["spanish native", "english intermediate"],
    programming_Languages: ["Javascript", "HTML", "CSS"],
    aboutme:
      "Me llamo María Rodriguez, estudié en la Universidad de Buenos Aires, Licenciatura en Informática.",
    programming_level: "Mid-level",
    CV: true,
    softskills: ["Problem Solving", "Creativity", "Adaptability"],
    profile_picture:
      "https://images.unsplash.com/photo-1573166953836-06864dc70a21?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=988&q=80",
  },
  {
    id: 3,
    name: "Carlos",
    lastName: "Gomez",
    birthdate: "1988-08-15",
    age: 35,
    working: true,
    country: "Mexico",
    email: "carlos.gomez@gmail.com",
    degree: "systems engineering",
    specialization: "Backend Developer",
    languages: ["spanish native", "english advanced"],
    programming_Languages: ["Java", "SQL", "Python"],
    aboutme:
      "Me llamo Carlos Gomez, estudié en la Universidad Autónoma de México, Ingeniería en Sistemas.",
    programming_level: "Senior",
    CV: true,
    softskills: ["Leadership", "Teamwork", "Critical Thinking"],
    profile_picture:
      "https://plus.unsplash.com/premium_photo-1661764406095-b2aabae753ba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2370&q=80",
  },
  {
    id: 4,
    name: "Luisa",
    lastName: "Martinez",
    birthdate: "1992-11-07",
    age: 30,
    working: true,
    country: "Colombia",
    email: "luisa.martinez@gmail.com",
    degree: "Software Engineer",
    specialization: "Data Science",
    languages: ["spanish native", "english advanced"],
    programming_Languages: ["Python", "R", "SQL"],
    aboutme:
      "Me llamo Luisa Martinez, estudié en la Universidad de Los Andes, Ingeniería de Software.",
    programming_level: "Mid-level",
    CV: true,
    softskills: ["Analytical Skills", "Mathematics", "Problem Solving"],
    profile_picture:
      "https://images.unsplash.com/photo-1573497161161-c3e73707e25c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=987&q=80",
  },
  {
    id: 5,
    name: "Diego",
    lastName: "Santos",
    birthdate: "1986-12-12",
    age: 36,
    working: true,
    country: "Spain",
    email: "diego.santos@gmail.com",
    degree: "computer science",
    specialization: "AI Developer",
    languages: ["spanish native", "english fluent"],
    programming_Languages: ["Python", "C++", "Java"],
    aboutme:
      "Me llamo Diego Santos, estudié en la Universidad Politécnica de Madrid, Ciencias de la Computación.",
    programming_level: "Senior",
    CV: true,
    softskills: ["Critical Thinking", "Mathematics", "Machine Learning"],
    profile_picture:
      "https://images.unsplash.com/photo-1517849845537-4d257902454a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1335&q=80",
  },
  {
    id: 6,
    name: "Patricia",
    lastName: "Lopez",
    birthdate: "1994-06-10",
    age: 29,
    working: true,
    country: "Peru",
    email: "patricia.lopez@gmail.com",
    degree: "information technology",
    specialization: "systems analyst",
    languages: ["spanish native", "english intermediate"],
    programming_Languages: ["Java", "Python", "SQL"],
    aboutme:
      "Me llamo Patricia Lopez, estudié en la Universidad de Lima, Tecnología de la Información.",
    programming_level: "Mid-level",
    CV: true,
    softskills: ["Analytical Skills", "Problem Solving", "Communication"],
    profile_picture: "https://link_to_patricia_picture",
  },
  {
    id: 7,
    name: "Ernesto",
    lastName: "Gutierrez",
    birthdate: "1989-02-28",
    age: 34,
    working: false,
    country: "Uruguay",
    email: "ernesto.gutierrez@gmail.com",
    degree: "software engineer",
    specialization: "mobile developer",
    languages: ["spanish native", "english advanced"],
    programming_Languages: ["Java", "Swift", "Kotlin"],
    aboutme:
      "Me llamo Ernesto Gutierrez, estudié en la Universidad de la República, Ingeniería de Software.",
    programming_level: "Senior",
    CV: false,
    softskills: ["Creativity", "Problem Solving", "Time Management"],
    profile_picture: "https://link_to_ernesto_picture",
  },
  {
    id: 8,
    name: "Carmen",
    lastName: "Rios",
    birthdate: "1997-09-05",
    age: 25,
    working: true,
    country: "Spain",
    email: "carmen.rios@gmail.com",
    degree: "computer science",
    specialization: "AI developer",
    languages: ["spanish native", "english fluent"],
    programming_Languages: ["Python", "R", "Java"],
    aboutme:
      "Me llamo Carmen Rios, estudié en la Universidad de Sevilla, Ciencias de la Computación. Soy una persona muy creativa y me encanta resolver problemas. Me gustaría trabajar en una empresa que me permita desarrollarme profesionalmente para eso estoy estudiando un máster en Inteligencia Artificial, y llevo 2 años trabajando en un proyecto de investigación en la universidad, gane una beca para trabajar en el proyecto entre una competencia de mas de 500 personas de todo el mundo, soy la mejor, aguante yo, metallica, y nadie mas. hola hola hola hola hola hola hola hola hola hola hola hola hola hola hola hola hola",
    programming_level: "Junior",
    CV: true,
    softskills: ["Analytical Skills", "Critical Thinking", "Mathematics"],
    profile_picture: "https://link_to_carmen_picture",
  },
  {
    id: 9,
    name: "Alfredo",
    lastName: "Ramirez",
    birthdate: "1991-12-17",
    age: 31,
    working: false,
    country: "Mexico",
    email: "alfredo.ramirez@gmail.com",
    degree: "information systems",
    specialization: "fullstack developer",
    languages: ["spanish native", "english intermediate"],
    programming_Languages: ["Javascript", "Python", "SQL"],
    aboutme:
      "Me llamo Alfredo Ramirez, estudié en el Instituto Politécnico Nacional, Sistemas Informáticos.",
    programming_level: "Mid-level",
    CV: false,
    softskills: ["Teamwork", "Communication", "Problem Solving"],
    profile_picture: "https://link_to_alfredo_picture",
  },
  {
    id: 10,
    name: "Rosario",
    lastName: "Vega",
    birthdate: "1992-04-30",
    age: 31,
    working: true,
    country: "Chile",
    email: "rosario.vega@gmail.com",
    degree: "computer engineering",
    specialization: "backend developer",
    languages: ["Spanish Native", "English Advanced"],
    programming_Languages: ["Python", "Java", "SQL"],
    aboutme:
      "Me llamo Rosario Vega, estudié en la Universidad de Chile, Ingeniería Informática.",
    programming_level: "Senior",
    CV: true,
    softskills: ["Leadership", "Critical Thinking", "Time Management"],
    profile_picture: "https://link_to_rosario_picture",
  },
];

//id, name, lastName, birthdate, age, working, country, email, degree, specialization, languages, programming_Languages, aboutme, programming_level, CV, softskills, profile_picture

export { jobsTemplate, usersTemplate };
