"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/src/app/components/NavBar/NavBar";
import { ThemeProvider } from "next-themes";
import { useTheme } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TechTalentHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider enableSystem={true} attribute="class">
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
